version: "3.9"

services:
  #new app (angular_app)
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./angularApp/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://localhost:3316/formulario?serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=sale92
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: formulario
      MYSQL_PASSWORD: sale92
      MYSQL_ROOT_PASSWORD: sale92